package com.learning.careerconnect.Model

/**
{
    "status": true,
    "data": [
        "Ambāla",
        "Āsandh",
        "Ateli Mandi",
        "Bahādurgarh",
        "Bara Uchāna",
        "Barwāla",
        "Bāwal",
        "Beri Khās",
        "Bhiwani",
        "Bhiwāni",
        "Bilāspur",
        "Būriya",
        "Charkhi Dādri",
        "Chhachhrauli",
        "Dabwāli",
        "Dhāruhera",
        "Ellenabad",
        "Faridabad",
        "Faridabad District",
        "Farrukhnagar",
        "Fatehābād",
        "Fatehabad District",
        "Fīrozpur Jhirka",
        "Gharaunda",
        "Gohāna",
        "Gorakhpur",
        "Gurgaon",
        "Hānsi",
        "Hasanpur",
        "Hisar",
        "Hisār",
        "Hodal",
        "Inda Chhoi",
        "Indri",
        "Jagādhri",
        "Jākhal",
        "Jhajjar",
        "Jīnd",
        "Kaithal",
        "Kalānaur",
        "Kālānwāli",
        "Kanīna Khās",
        "Karnāl",
        "Kharkhauda",
        "Kheri Sāmpla",
        "Kurukshetra",
        "Lādwa",
        "Lohāru",
        "Maham",
        "Mahendragarh",
        "Mandholi Kalān",
        "Mustafābād",
        "Narāyangarh",
        "Nārnaul",
        "Nārnaund",
        "Narwāna",
        "Nīlokheri",
        "Nūh",
        "Palwal",
        "Panchkula",
        "Pānīpat",
        "Panipat",
        "Pataudi",
        "Pehowa",
        "Pinjaur",
        "Pūnāhāna",
        "Pūndri",
        "Radaur",
        "Rānia",
        "Ratia",
        "Rewāri",
        "Rewari District",
        "Rohtak",
        "Safidon",
        "Samālkha",
        "Shādīpur Julāna",
        "Shāhābād",
        "Sirsa",
        "Sohna",
        "Sonīpat",
        "Tāoru",
        "Thānesar",
        "Tohāna",
        "Toshām",
        "Uklāna",
        "Yamunanagar",
        "Yamunānagar"
    ]
}
*/
data class SingleCityOM(
    var `data`: List<String?>?,
    var status: Boolean? // true
)